package dto

const (
	ErrorCodeValidation                = "validation_error"
	ErrorCodeUnauthorized              = "unauthorized"
	ErrorCodeForbidden                 = "forbidden"
	ErrorCodeInactiveUser              = "inactive_user"
	ErrorCodeCurrentPasswordInvalid    = "current_password_invalid"
	ErrorCodeNewPasswordSameAsCurrent  = "new_password_same_as_current"
	ErrorCodePasswordPolicyViolation   = "password_policy_violation"
	ErrorCodeBookingTooEarlyToComplete = "booking_too_early_to_complete"
	ErrorCodeBookingForbidden          = "booking_forbidden"
	ErrorCodeBookingAlreadyEnded       = "booking_already_ended"
	ErrorCodeBookingCancelNotAllowed   = "booking_cancel_not_allowed"
	ErrorCodeBookingOutsideWorkday     = "booking_outside_workday"
	ErrorCodeBookingInUnavailability   = "booking_in_unavailability"
	ErrorCodeBookingConflict           = "booking_conflict"
	ErrorCodeBookingResourceUnavailable = "booking_resource_unavailable"
	ErrorCodeBookingRuleNotConfigured  = "booking_rule_not_configured"
	ErrorCodeBookingLimitExceeded      = "booking_limit_exceeded"
	ErrorCodeBookingHorizonExceeded    = "booking_horizon_exceeded"
	ErrorCodeBookingStartInPast        = "booking_start_in_past"
	ErrorCodeBookingBatchTooLarge      = "booking_batch_too_large"
	ErrorCodeBookingBatchDuplicateDate = "booking_batch_duplicate_date"
	ErrorCodeBookingBatchInvalid       = "booking_batch_invalid"
	ErrorCodeNotFound                  = "not_found"
	ErrorCodeConflict                  = "conflict"
	ErrorCodeInternal                  = "internal_error"
)
